---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Invisible.
--- DateTime: 5/26/2025 9:27 PM
---




--[[SMODS.Booster {
    key = "black_market",
    loc_txt = {
        name = "Black Market Pack",
        text = " a "
    },
    discovered = true,
    unlocked = true,
    config = { extra = {}},
    rarity = 2,
    atlas = "TextureAtlasJokers",
    pos = { x = 0, y = 0},
    config = { extra = 2, choose = 1},
    cost = 6,
    weight = 1,
    draw_hand = true,

}
--]]

SMODS.Booster{
    key = 'black_market',
    atlas = 'TextureAtlasConsumables',
    group_key = "k_visibility_booster_group",
    pos = { x = 0, y = 3 },
    discovered = true,
    loc_txt= {
        name = 'Black Market Pack',
        text = { "Pick {C:attention}#1#{} card out",
                 "{C:attention}#2#{} Visibility jokers!", },
    },

    draw_hand = false,
    config = {
        extra = 3,
        choose = 1,
    },

    loc_vars = function(self, info_queue, card)
        return { vars = { card.ability.choose, card.ability.extra } }
    end,
    weight = 0.5,
    cost = 10,
    kind = "VisibilityPack",

    create_card = function(self, card, i)
        ease_background_colour(HEX("ffac00"))
        return SMODS.create_card({
            set = "Visibility",
            area = G.pack_cards,
            skip_materialize = true,
            soulable = true,
        })
    end,
    select_card = 'jokers',

    in_pool = function() return true end
}

SMODS.Booster{
    key = 'c_black_market',
    atlas = 'TextureAtlasJokers',
    group_key = "k_visib/ility_booster_group",
    pos = { x = 1, y = 1 },
    discovered = true,
    loc_txt= {
        name = 'Black Market Pack',
        text = { "Pick {C:attention}#1#{} card out",
                 "{C:attention}#2#{} Visibility jokers!", },
    },

    draw_hand = false,
    config = {
        extra = 3,
        choose = 1,
    },

    loc_vars = function(self, info_queue, card)
        return { vars = { card.ability.choose, card.ability.extra } }
    end,
    weight = 0.66,
    cost = 10,
    kind = "VisibilityPack",

    create_card = function(self, card, i)
        ease_background_colour(HEX("ffac00"))
        return SMODS.create_card({
            set = "c_Visibility",
            area = G.pack_cards,
            skip_materialize = true,
            soulable = true,
        })
    end,
    select_card = 'jokers',

    in_pool = function() return true end
}